import AlgerianWomenImage from './images/algerianWomen.png';
import SkrikImage from './images/skrik.png';
import ButlerImage from './images/butler.png';
import Img4 from './images/img4.png';
import Img5 from './images/img5.png';
import Img6 from './images/img6.png';
import Img7 from './images/img7.png';
import Img8 from './images/img8.png';
import Img9 from './images/img9.png';

const lots = [
  {
    id: 1,
    number: '001',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'London',
    event: "Sotheby's",
    category: "Paintings",
    image: AlgerianWomenImage,
  },
  {
    id: 2,
    number: '002',
    title: '«Крик» Эдварда Мунка',
    price: '250 000 RUB',
    city: 'Hong Kong',
    event: "Christie's",
    category: "Paintings",
    image: SkrikImage,
  },
  {
    id: 3,
    number: '003',
    title: '«Поющий дворецкий»',
    price: '250 000 RUB',
    city: 'Dubai',
    event: "Sotheby's",
    category: "Paintings",
    image: ButlerImage,
  },
  {
    id: 4,
    number: '004',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'New York',
    event: "Phillips contemporary",
    category: "Coins",
    image: Img4,
  },
  {
    id: 5,
    number: '005',
    title: '«Крик» Эдварда Мунка',
    price: '250 000 RUB',
    city: 'Hong Kong',
    event: "Sotheby's",
    category: "Porcelain",
    image: Img5,
  },
  {
    id: 6,
    number: '006',
    title: '«Поющий дворецкий»',
    price: '250 000 RUB',
    city: 'Paris',
    event: "Sotheby's",
    category: "Glass, crystal",
    image: Img6,
  },
  {
    id: 7,
    number: '007',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'Dubai',
    event: "Christie's",
    category: "Paintings",
    image: Img7,
  },
  {
    id: 8,
    number: '008',
    title: '«Крик» Эдварда Мунка',
    price: '250 000 RUB',
    city: 'London',
    event: "Phillips contemporary",
    category: "Paintings",
    image: Img8,
  },
  {
    id: 9,
    number: '009',
    title: '«Поющий дворецкий»',
    price: '250 000 RUB',
    city: 'Dubai',
    event: "Sotheby's",
    category: "Paintings",
    image: Img9,
  },
  {
    id: 10,
    number: '010',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'New York',
    event: "Sotheby's",
    category: "Paintings",
    image: AlgerianWomenImage,
  },
  {
    id: 11,
    number: '011',
    title: '«Крик» Эдварда Мунка',
    price: '250 000 RUB',
    city: 'Hong Kong',
    event: "Phillips contemporary",
    category: "Paintings",
    image: SkrikImage,
  },
  {
    id: 12,
    number: '012',
    title: '«Поющий дворецкий»',
    price: '250 000 RUB',
    city: 'London',
    event: "Sotheby's",
    category: "Porcelain",
    image: ButlerImage,
  },
  {
    id: 13,
    number: '013',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'Paris',
    event: "Christie's",
    category: "Coins",
    image: Img4,
  },
  {
    id: 14,
    number: '014',
    title: '«Крик» Эдварда Мунка',
    price: '250 000 RUB',
    city: 'Dubai',
    event: "Sotheby's",
    category: "Paintings",
    image: Img5,
  },

  {
    id: 15,
    number: '015',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'London',
    event: "Phillips contemporary",
    category: "Glass, crystal",
    image: AlgerianWomenImage,
  },
  {
    id: 16,
    number: '016',
    title: '«Крик» Эдварда Мунка',
    price: '250 000 RUB',
    city: 'Hong Kong',
    event: "Sotheby's",
    category: "Paintings",
    image: SkrikImage,
  },
  {
    id: 17,
    number: '017',
    title: '«Поющий дворецкий»',
    price: '250 000 RUB',
    city: 'London',
    event: "Christie's",
    category: "Paintings",
    image: ButlerImage,
  },
  {
    id: 18,
    number: '018',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'New York',
    event: "Sotheby's",
    category: "Paintings",
    image: Img4,
  },
  {
    id: 19,
    number: '019',
    title: '«Крик» Эдварда Мунка',
    price: '270 000 RUB',
    city: 'London',
    event: "Phillips contemporary",
    category: "Porcelain",
    image: Img5,
  },
  {
    id: 20,
    number: '020',
    title: '«Поющий дворецкий»',
    price: '25 000 RUB',
    city: 'Dubai',
    event: "Phillips contemporary",
    category: "Paintings",
    image: Img6,
  },
  {
    id: 21,
    number: '021',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '20 000 RUB',
    city: 'Hong Kong',
    event: "Sotheby's",
    category: "Coins",
    image: Img7,
  },
  {
    id: 22,
    number: '022',
    title: '«Крик» Эдварда Мунка',
    price: '320 000 RUB',
    city: 'Paris',
    event: "Christie's",
    category: "Paintings",
    image: Img8,
  },
  {
    id: 23,
    number: '023',
    title: '«Поющий дворецкий»',
    price: '150 000 RUB',
    city: 'London',
    event: "Phillips contemporary",
    category: "Paintings",
    image: Img9,
  },
  {
    id: 24,
    number: '024',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '220 000 RUB',
    city: 'London',
    event: "Phillips contemporary",
    category: "Glass, crystal",
    image: AlgerianWomenImage,
  },
  {
    id: 25,
    number: '025',
    title: '«Крик» Эдварда Мунка',
    price: '255 000 RUB',
    city: 'New York',
    event: "Sotheby's",
    category: "Paintings",
    image: SkrikImage,
  },
  {
    id: 26,
    number: '026',
    title: '«Поющий дворецкий»',
    price: '31 000 RUB',
    city: 'Hong Kong',
    event: "Sotheby's",
    category: "Paintings",
    image: ButlerImage,
  },
  {
    id: 27,
    number: '027',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '22 000 RUB',
    city: 'Dubai',
    event: "Christie's",
    category: "Porcelain",
    image: Img4,
  },
  {
    id: 28,
    number: '028',
    title: '«Крик» Эдварда Мунка',
    price: '84 000 RUB',
    city: 'London',
    event: "Phillips contemporary",
    category: "Paintings",
    image: Img5,
  },
  {
    id: 29,
    number: '029',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '72 000 RUB',
    city: 'Paris',
    event: "Sotheby's",
    category: "Paintings",
    image: AlgerianWomenImage,
  },
  {
    id: 30,
    number: '030',
    title: '«Крик» Эдварда Мунка',
    price: '14 000 RUB',
    city: 'London',
    event: "Sotheby's",
    category: "Paintings",
    image: SkrikImage,
  },
  {
    id: 31,
    number: '031',
    title: '«Поющий дворецкий»',
    price: '15 000 RUB',
    city: 'Hong Kong',
    event: "Sotheby's",
    category: "Paintings",
    image: ButlerImage,
  },
  {
    id: 32,
    number: '032',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '43 000 RUB',
    city: 'London',
    event: "Christie's",
    category: "Glass, crystal",
    image: Img4,
  },
  {
    id: 33,
    number: '033',
    title: '«Крик» Эдварда Мунка',
    price: '89 000 RUB',
    city: 'Dubai',
    event: "Phillips contemporary",
    category: "Porcelain",
    image: Img5,
  },
  {
    id: 34,
    number: '034',
    title: '«Поющий дворецкий»',
    price: '13 000 RUB',
    city: 'New York',
    category: "Paintings",
    event: "Sotheby's",
    image: Img6,
  },
  {
    id: 35,
    number: '035',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'London',
    event: "Phillips contemporary",
    category: "Paintings",
    image: Img7,
  },
  {
    id: 36,
    number: '036',
    title: '«Крик» Эдварда Мунка',
    price: '250 000 RUB',
    city: 'Hong Kong',
    event: "Sotheby's",
    category: "Paintings",
    image: Img8,
  },
  {
    id: 37,
    number: '037',
    title: '«Поющий дворецкий»',
    price: '60 000 RUB',
    city: 'Paris',
    event: "Christie's",
    category: "Paintings",
    image: Img9,
  },
  {
    id: 38,
    number: '038',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '250 000 RUB',
    city: 'London',
    event: "Sotheby's",
    category: "Paintings",
    image: AlgerianWomenImage,
  },
  {
    id: 39,
    number: '039',
    title: '«Крик» Эдварда Мунка',
    price: '70 000 RUB',
    city: 'Dubai',
    event: "Phillips contemporary",
    category: "Coins",
    image: SkrikImage,
  },
  {
    id: 40,
    number: '040',
    title: '«Поющий дворецкий»',
    price: '250 000 RUB',
    city: 'Paris',
    event: "Sotheby's",
    image: ButlerImage,
  },
  {
    id: 41,
    number: '041',
    title: '«Алжирские женщины (Версия О)», Пабло Пикассо',
    price: '50 000 RUB',
    city: 'Hong Kong',
    event: "Phillips contemporary",
    category: "Porcelain",
    image: Img4,
  },
  {
    id: 42,
    number: '042',
    title: '«Крик» Эдварда Мунка',
    price: '30 000 RUB',
    city: 'New York',
    event: "Christie's",
    category: "Coins",
    image: Img5,
  },
];

export default lots;